[package]
name = "zskanz/synchronizer"
description = "Debounce use"
version = "3.0.1"
license = "MIT"
authors = ["Skanz"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
repository = "https://github.com/zskanz/Synchronizer"
exclude = ["*.zip", "aftman.toml", "selene.toml", "Packages", "wally.lock", "src", "default.project.json"]

[dependencies]